### ISSUE TITLE
Self Referencing Links and Mutual Links Add Extra Text

### ISSUE THREAD

**Issue by natefrisch01** [natefrisch01/Graph-Link-Types#1]
![image](https://github.com/natefrisch01/Graph-Link-Types/assets/44580969/88309856-b3a2-492b-9842-91675e515cb7)

**Comment by natefrisch01** [comment]
![image](https://github.com/natefrisch01/Graph-Link-Types/assets/44580969/d3423b50-5e9a-405d-aae2-f30a9b228604)
I made a quick fix, but it doesn't look pretty. I'm leaving this as an issue until we have a better solution.

**Comment by WHG555** [comment]
你准备添加双向的箭头么？  
![image](https://github.com/natefrisch01/Graph-Link-Types/assets/26180549/c63ea26d-e66c-48d7-9137-1e81919e7f3e)
类似于这样的

**Comment by natefrisch01** [comment]
![image](https://github.com/natefrisch01/Graph-Link-Types/assets/44580969/88d3c00e-9249-4a28-ae74-d95ebf9ddada)

**Comment by natefrisch01** [comment]
Yep... it's painful, but I'm making progress.
