### ISSUE TITLE
Plugin still spams console on startup

### ISSUE THREAD

**Issue by FeralFlora** [natefrisch01/Graph-Link-Types#9]
I know the last release says "cleanup logs", but the plugin still spams the console with hundreds of:

`"New metadata, drawing graph link types."`

when I start Obsidian. See screenshot:
<img width="1024" alt="image" src="https://github.com/natefrisch01/Graph-Link-Types/assets/33608083/e0e8959e-bf00-4ace-bb45-9aabbc9ece3c">

**Comment by natefrisch01** [comment]
Alright, I put out a new release that should have that fixed. Thank you for letting me know, and please let me know if you find anything else - thanks!

**Comment by natefrisch01** [comment]
Sorry, I didn't mean to close this until I knew it worked for you! It's interesting that it was spamming it on startup for you, because it should only do that when new metadata is added by dataview...

**Comment by FeralFlora** [comment]
> Sorry, I didn't mean to close this until I knew it worked for you! 

That's okay. I tested it now: Updated and restarted, and there was no console log from Graph link types this time. So it seems to have worked.


> It's interesting that it was spamming it on startup for you, because it should only do that when new metadata is added by dataview...

Hmm, I see, that is interesting then. It was happening every startup. Dataview always indexes the vault on startup for me. Isn't that normal?

**Comment by natefrisch01** [comment]
Yes, I believe so. The have 2 different events that I'm attached to, one is the initial indexing, and one is the new metadata. I'm thinking I shouldn't attach to the new metadata event until the indexing is over, because it seems like while indexing the new metadata event gets called a ton of times. Thanks for your help, I will try to account for this soon!
